# Generated by Django 4.0.1 on 2022-01-07 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_properties_renter_transaction_delete_duerents'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='joined',
            field=models.DateField(default=datetime.date(2022, 1, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 7)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
