# Generated by Django 4.0.1 on 2022-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_renter_joined_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='rent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
