# Generated by Django 4.0.1 on 2022-01-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_renter_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='joined',
            new_name='dateJoined',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amtPaid',
            new_name='dues',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='totalRent',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.AddField(
            model_name='renter',
            name='dateLeft',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='renter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.renter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='renter',
            name='homeAddr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='renter',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.properties'),
        ),
    ]
