# Generated by Django 4.0.1 on 2022-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_renter_dateleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
