# Generated by Django 4.0.1 on 2022-01-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_transaction_dues_alter_transaction_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
