# Generated by Django 4.0.1 on 2022-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.AddField(
            model_name='renter',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
