# Generated by Django 4.0.1 on 2022-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_transaction_balance_renter_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
