# Generated by Django 4.0.1 on 2022-02-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_renter_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='rent',
            field=models.IntegerField(null=True),
        ),
    ]
